name: Analyze & Push

on:
  workflow_dispatch:

jobs:
  Analyze:
    runs-on: windows-latest

    steps:
    - name: Maximizing storage
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 8192
        root-reserve-mb: 4096
        temp-reserve-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependence
      run: |
        wget https://dl.androidaapt.com/aapt-windows.zip
        7z o aapt-windows.zip
        pip install -r requirements.txt

    - name: Download extract.erofs
      uses: robinraju/release-downloader@v1.10
      with:
        repository: "sekaiacg/erofs-utils"
        latest: true
        extract: true
        fileName: 'erofs-utils-*-Linux_x86_64-*.zip'

    - name: Download payload-dumper-go
      uses: robinraju/release-downloader@v1.10
      with:
        repository: "ssut/payload-dumper-go"
        latest: true
        extract: true
        fileName: 'payload-dumper-go_*_linux_amd64.tar.gz'

    - name: Remove files
      run: |
       rm *.tar.gz *.zip