name: Test

on:
  workflow_dispatch:

jobs:
  Analyze:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependence
      run: |
        pip install -r requirements.txt

    - name: Download extract.erofs
      uses: robinraju/release-downloader@v1.10
      with:
        repository: "sekaiacg/erofs-utils"
        latest: true
        extract: true
        fileName: 'erofs-utils-*-Linux_x86_64-*.zip'