name: TEST

on:
  workflow_dispatch:
    inputs:
      device:
        description: '设备类型 p/ph/f'
        required: true
      link:
        description: 'ROM 链接'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximizing storage
      uses: easimon/maximize-build-space@master
      with:
        swap-size-mb: 8192
        root-reserve-mb: 4096
        temp-reserve-mb: 4096
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'

    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Install dependence
      run: |
        sudo apt-get install -y android-sdk-build-tools
        pip install apkfile
        wget -O erofs-utils.zip https://github.com/sekaiacg/erofs-utils/releases/download/v1.7.1-231221/erofs-utils-v1.7.1-g64fa6832-Linux_x86_64-2312211134.zip
        unzip erofs-utils.zip
        rm erofs-utils.zip
        wget -O payload-dumper-go.tar.gz https://github.com/ssut/payload-dumper-go/releases/download/1.2.2/payload-dumper-go_1.2.2_linux_amd64.tar.gz
        tar -xvf payload-dumper-go.tar.gz
        rm payload-dumper-go.tar.gz

    - name: Download ROM
      run: |
        python main.py -d ${{ github.event.inputs.link }}

    - name: Switch device type
      run: |
        python main.py -t 0 ${{ github.event.inputs.device }}

    - name: Unzip payload.bin
      run: |
        python main.py -p
        rm *.zip

    - name: Unzip img
      run: |
        python main.py -i
        rm payload.bin
    
    - name: Unzip files
      run: |
        python imgfs.py